### ISSUE TITLE
Switch back to TypeScript

### ISSUE THREAD

**Issue by pcowgill** [clrfund/monorepo#10]

**Comment by proofoftom** [comment]
In regards to this, #11, and #12: I've rebuilt the boilerplate since the hackathon and removed the dependency on Quasar, since its Typescript support isn't production ready, and replaced it with Typescript Vue + Vuetify (for the material design component library). This seems to have squashed all of the bugs and has IDE support that is compatible when developing both the contracts and the frontend. I'm happy to migrate what we have over and give it a full QA. Here's the updated boilerplate: https://github.com/proofoftom/buidler-waffle-typechain-vue

**Comment by pcowgill** [comment]
Sounds good!!

**Comment by pcowgill** [comment]
Thoughts on a separate package.json for contracts vs front end?

**Comment by proofoftom** [comment]
I don't _think_ there will be a need, but am happy to go that direction without question if there is any conflict.

**Comment by pcowgill** [comment]
Yeah, there's definitely not a need - sometimes I just like it when looking at a new open source project to see which packages they're using for what. Helps with security audits, etc.

**Comment by pcowgill** [comment]
If we want `npm install` or `yarn` at the root to install everything, we could use `lerna`

**Comment by pcowgill** [comment]
We can probably move the dir structure convo over to https://github.com/clr-fund/contracts/issues/12
