### ISSUE TITLE
Sticky cart and navigation bar

### ISSUE THREAD

**Issue by xuhcc** [clrfund/monorepo#335]
The cart and navigation bar shouldn't scroll along with the page content.

**Comment by codeluggage** [comment]
Is this still an issue? I can't see any sticky elements on https://clr.fund in Firefox, Brave and Chrome. Checked with account disconnected, connected, and with a project in the cart.

**Comment by xuhcc** [comment]
This has not been implemented, and I'm not quite sure if it is desirable.

**Comment by codeluggage** [comment]
> This has not been implemented, and I'm not quite sure if it is desirable.

Hmm, the original description reads `The cart and navigation bar shouldn't` - was that actually meant to be `should`? The title of the issue compared with the description did make me wonder. 

From my very limited interaction, it does seem like a sticky cart could be useful if a common use case is to spend lots of time scrolling and adding. It felt a little "hidden away" up in the corner when I was trying it out, because of the time spent exploring further down the page.

**Comment by xuhcc** [comment]
The description is correct. I thought that sticky cart could be more convenient, but I wasn't quite sure about that.
If you also think that sticky cart is better, this can be easily implemented. Actually I already did that, here's the preview https://bafybeicrsiiqaczrrcrqpg3zobvx4osoiei7cxxnyrgdur2ozzgynii7ni.ipfs.dweb.link/#/
