### ISSUE TITLE
Add CSS framework / library?

### ISSUE THREAD

**Issue by samajammin** [clrfund/monorepo#351]
@xuhcc curious to get your thoughts on potentially adding a CSS framework to help speed up frontend development.

Given that the current application primarily uses a class-based approach to CSS styling, I'd suggest a library that provides utility classes out of the box, like [Tailwind](https://tailwindcss.com/).

If you're on board, I'd start by adding things gradually, e.g. by just adding margin & padding utilities:
- https://tailwindcss.com/docs/margin
- https://tailwindcss.com/docs/padding

Open to your ideas/question/concerns here. Not trying to push one particular approach, figure this could be a way to open up a dialogue.

Looking forward to hearing what you think!

**Comment by xuhcc** [comment]
You'll end up using CSS anyway because the library doesn't provide classes for everything, so what's the point? These things just complicate the code, add bloat and make it harder for new people to contribute to the project.

In 5 years no one will use tailwind, but CSS is here to stay. Just use CSS
